name: Cp files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: realityfamily-local-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Cp files
      run: cp -r * /home/cbi/pentagramma/src
